name: ttf-gas-pipeline

volumes:
  postgres-data:
  kestra-data:
  project-code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}
  gcloud-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.config/gcloud
  dbt-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.dbt

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kestra"]
      interval: 10s
      retries: 10

  kestra:
    image: kestra/kestra:latest
    user: root
    command: server standalone --worker-thread=8
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kestra/flows:/app/flows
      - project-code:/app/project
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tutorial:
            enabled: false
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volume-enabled: true
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy